### ISSUE TITLE
已经挂了。

### ISSUE THREAD

**Issue by zyzll1234** [hlc1209/Taobao_overseas#1]

**Comment by hlc1209** [comment]
我找了个东西测试了没有挂啊。挂了的链接给我我测试一下

**Comment by hlc1209** [comment]
> _No description provided._

我找了个东西测试了没有挂啊。挂了的链接给我我测试一下

**Comment by zyzll1234** [comment]
我ip因为链接回深圳ip，被临时封禁了，明天给你发截图，我商品现在完全没法浏览。谢谢
在2019年9月29日 05:28，hlc1209<notifications@github.com> 写道：

No description provided.

我找了个东西测试了没有挂啊。挂了的链接给我我测试一下

**Comment by hlc1209** [comment]
> 我ip因为链接回深圳ip，被临时封禁了，明天给你发截图，我商品现在完全没法浏览。谢谢 在2019年9月29日 05:28，hlc1209<notifications@github.com> 写道： No description provided. 我找了个东西测试了没有挂啊。挂了的链接给我我测试一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

只要URL就可以。可以不要截图
另外，我这个不防ip被禁，只可避免“因国家出口法律”而被跳转到“海外阻断Detail 中国站”的情况。
