### ISSUE TITLE
This Script is not working now

### ISSUE THREAD

**Issue by rioto9858** [hlc1209/Taobao_overseas#2]
Test Date: 2019/12/18
The script is not working.

**Comment by hlc1209** [comment]
You should report your browser version first, and attach the URL here.

**Comment by Uio96** [comment]
@hlc1209 I faced the same problem. The chrome version is 89.0.4389.90 (Official Build) (64-bit). A test URL is like https://item.taobao.com/item.htm?spm=a230r.1.14.28.128f6218iOYccU&id=599554541302&ns=1&abbucket=17#detail

**Comment by hlc1209** [comment]
I have checked the URL you sent me. It's a known issue caused by Google/Chromium. I'm unable to resolve the issue on my side. 

However, you can still get a temporary solution by trying to open the link multiple times.

This script won't work every time, but it works in the end.
