### ISSUE TITLE
对天猫阻断无效

### ISSUE THREAD

**Issue by ywang530** [hlc1209/Taobao_overseas#3]
版本1.2.1
店家如果是天猫的话 会显示天猫阻断detail，淘宝个体商户没有问题。
访问以下网址出现了天猫阻断：
https://detail.tmall.com/item.htm?spm=a230r.1.14.9.3f44197dYrga0B&id=579620464254&ad_id=&am_id=&cm_id=140105335569ed55e27b&pm_id=&abbucket=14

**Comment by hlc1209** [comment]
经测试，此脚本依旧有效。注意：如果出现阻断失败，可以多次尝试打开商品链接。此问题是由于Google/Chromium的判断机制造成的，无法在我这边修复。
